### ISSUE TITLE
请问这套代码支持 攀藤g10 吗?

### ISSUE THREAD

**Issue by wasas** [lewei50/lua-on-nodemcu#1]
https://github.com/lewei50/lua/tree/master/demo/ESP8266-PMS5XXX-OLED

**Comment by lewei50** [comment]
你好：
如果G10兼容G5，应该就可以支持。
 
 
------------------ 原始邮件 ------------------
发件人: "wasas"<notifications@github.com>;
发送时间: 2017年3月2日(星期四) 上午9:24
收件人: "lewei50/lua"<lua@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [lewei50/lua] 请问这套代码支持 攀藤g10 吗? (#1)

 

https://github.com/lewei50/lua/tree/master/demo/ESP8266-PMS5XXX-OLED

**Comment by wasas** [comment]
买的 G10 结果卖家给发成 G7 了, 实测是支持 G7 的, 估计 G10 也是没问题的了...
